_BASE_: "Base-TensorMask.yaml"
MODEL:  # use weights from Tensormask paper
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/TensorMask/tensormask_R_50_FPN_6x/153538791/model_final_e8df31.pkl"
  TENSOR_MASK:
    NUM_CLASSES: 8  # Dataset uses 1-based indexing. 0 Could be used for noise
    SCORE_THRESH_TEST: 0.5
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  MAX_ITER: 20000
INPUT:
  MAX_SIZE_TEST: 1500
  MIN_SIZE_TEST: 1200
TEST:
  DETECTIONS_PER_IMAGE: 300
  EVAL_PERIOD: 500
CAP:
  PICKLE_PATH: "./data/copy_and_paste/pickled_objs/cap_dataset.pkl"
  PATCH_POOL: "data/copy_and_paste/objs/"
  MAX_RESOLUTION: (1600, 1300)  # Limit for Tesla P100 with 16 GB VRAM
  POOLS_CFG: "configs/insects_cap_pool_config.yaml"
  BACKGROUND_ANNO: "data/copy_and_paste/backgrounds/background_anno.json"
  BACKGROUND_DIR: "data/copy_and_paste/backgrounds/"
  COLLECTION_BOX_GENERATOR:
    P: 0.6
    POOL_NAME: "collection_box_pool"
    MAX_N_OBJS_PER_IMAGE: 150
    SKIP_IF_OVERLAP_RANGE: (0.1, 0.2)
  RANDOM_GENERATOR:
    P: 0.4
    POOL_NAME: "random_pool"
    MAX_N_OBJS_PER_IMAGE: 30
    SKIP_IF_OVERLAP_RANGE: (0.1, 0.2)
    ASSUMED_OBJ_SIZE: 70000
  HIGH_QUALITY_GENERATOR:  # not yet implemented
    P: 0.0
    POOL_NAME: "hq_pool"
    MAX_N_OBJS_PER_IMAGE: 150
    SKIP_IF_OVERLAP_RANGE: (0.1, 0.1)
  AUGMENT:
    P: 0.7
VERSION: 2