_BASE_: "Base-TensorMask.yaml"
CAP:  # TODO Move to dataset
  PICKLE_PATH: "./data/copy_and_paste/pickled_objs/cap_dataset.pkl"
  PATCH_POOL: "data/copy_and_paste/objs/"
  MAX_RESOLUTION: (1600, 1300)  # TODO unify
  POOLS_CFG: "configs/insects_cap_pool_config.yaml"
  BACKGROUND_ANNO: "data/copy_and_paste/backgrounds/background_anno.json"
  BACKGROUND_DIR: "data/copy_and_paste/backgrounds/"
  COLLECTION_BOX_GENERATOR:
    P: 0.6
    POOL_NAME: "collection_box_pool"
    MAX_N_OBJS_PER_IMAGE: 150
    SKIP_IF_OVERLAP_RANGE: (0.1, 0.2)
  RANDOM_GENERATOR:
    P: 0.4
    POOL_NAME: "random_pool"
    MAX_N_OBJS_PER_IMAGE: 30
    SKIP_IF_OVERLAP_RANGE: (0.1, 0.2)
    ASSUMED_OBJ_SIZE: 70000
  HIGH_QUALITY_GENERATOR:  # not yet implemented
    P: 0.0
    POOL_NAME: "hq_pool"
    MAX_N_OBJS_PER_IMAGE: 150
    SKIP_IF_OVERLAP_RANGE: (0.1, 0.1)
  AUGMENT: 
    P: 0.7
DATASETS:
  TEST: ("validation_boxes", )
VERSION: 2