collection_box_pool:
  Mesembryhmus_purpuralis:
    1: 3
    0.5: 6
  Smerinthus_ocellata:
    1 : 1
    0.5: 3
    0.25: 5
  Acherontia_atroposa:
    1 : 1
    0.5: 3
    0.25: 5
  bug_proxy_1:
    1: 2
    0.5: 2
    0.25: 4
  bug_proxy_2:
    2: 1
    1: 3
    0.5: 4
  bug_proxy_3:
    2: 1
    1: 2
    0.5: 4
  Trichotichnus:
    3: 2
    2: 4
    1: 4
random_pool:
  Mesembryhmus_purpuralis:
    2: 1
    1: 2
    0.5: 2
  Smerinthus_ocellata:
    1 : 1
    0.5: 2
    0.25: 2
  Acherontia_atroposa:
    1 : 1
    0.5: 2
    0.25: 2
  bug_proxy_1:
    2: 1
    1: 1
    0.5: 2
    0.25: 2 
  bug_proxy_2:
    2: 1
    1: 2
    0.5: 2
  bug_proxy_3:
    2: 1
    1: 2
    0.5: 2
  Trichotichnus:
    3: 2
    2: 4
    1: 4
hq_pool:
